version: '3'

services:
  api: 
    container_name: api
    build:
      context: .
      dockerfile: ./dockerfile
    tty: true
    ports:
      - 8080:8080
    restart: always
    volumes:
      - type: bind
        source: .
        target: /api
    command: sh -c "npm run start:dev"