version: '3'

services:
  api: 
    container_name: api
    build:
      context: .
      dockerfile: ./dockerfile
    tty: true
    ports:
      - 8000:8000
    restart: always
    volumes:
      - type: bind
        source: .
        target: /api

  postgresql:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres